config/routes.rb
Rails.application.routes.draw do
  root 'portfolios#index'
  devise_for :users

  resources :portfolios, except: [:new] do
    resources :stocks, only: [:create, :destroy]
  end
end

app/models/portfolio.rb
# == Schema Information
#
# Table name: portfolios
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Portfolio < ActiveRecord::Base
  belongs_to :user
  has_many :stocks, dependent: :destroy

  validates :title, presence: true

  def stock_list
    stocks.inject([]) do |m, v|
      m << v.symbol
    end
  end

  def stock_count
    stocks.inject(0) do |m, v|
      m + v.count
    end
  end
end

app/controllers/portfolios_controller.rb
# == Schema Information
#
# Table name: portfolios
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PortfoliosController < ApplicationController
  
  # Generates 404 page if the current portfolio is not exists or user is not an owner.
  before_action :portfolio_exists?, only: [:show, :edit, :update, :destroy]

  # Redirects to portfolios path (if user is not an owner of the current portfolio)
  before_action :user_owns_portfolio?, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  def index
    @portfolios = current_user.portfolios
    @empty_portfolio = Portfolio.new
  end

  # GET /portfolios/:id
  def show
    @stock = Stock.new
    gon.portfolio = {
      title:  @portfolio.title,
      stocks: @portfolio.stocks
    }
  end

  # GET /portfolios/:id/edit
  def edit
  end

  # POST /portfolios
  def create
    @portfolio = current_user.portfolios.create(permitted_params)

    if @portfolio.errors.empty?
      flash[:notice] = 'New portfolio created!'
      redirect_to portfolios_path
    else
      flash[:alert] = @portfolio.errors
      redirect_to portfolios_path
    end
  end

  # PATCH /portfolios/:id
  # PUT   /portfolios/:id
  def update
    if @portfolio.update(permitted_params)
      flash[:notice] = 'Portfolio successfully updated!'
      redirect_to portfolios_path
    else
      flash[:alert] = @portfolio.errors
      render 'edit'
    end
  end

  # DELETE /portfolios/:id
  def destroy
    if @portfolio.destroy
      flash[:notice] = 'Portfolio successfully destroyed!'
      redirect_to portfolios_path
    else
      flash[:alert] = @portfolio.errors
      redirect_to portfolios_path # TODO: redirect to last page
    end
  end

  private

  # Will render 404 page if the current portfolio is not exists or user is not an owner.
  def portfolio_exists?
    @portfolio = current_user.portfolios.find_by(id: params[:id])
    render(
      file: "#{Rails.root}/public/404",
      layout: false,
      status: :not_found
    ) if @portfolio.nil?
  end

 # Redirects to portfolios path (if user is not an owner of the current portfolio)
  def user_owns_portfolio?
    unless current_user.has_portfolio?(params[:id])
      flash[:alert] = {
        portfolio_controller: 'You are not an owner of the chosen portfolio.'
      }
      redirect_to portfolios_path
    end
  end

  def permitted_params
    params.require(:portfolio).permit(:title)
  end
end

app/views/portfolios/edit.html.slim
- provide(:title, 'Portfolio - Edit')

.page-content
  .mdl-grid.portfolio-edit
    .mdl-cell.mdl-cell--2-col
    .mdl-cell.mdl-cell--8-col

      div
        = form_for @portfolio, html: { class: 'portfolio-edit__form' } do |f|
          .mdl-textfield.mdl-js-textfield.portfolio-edit__title-field
            = f.text_field :title, class: 'mdl-textfield__input'
            = f.label      :title, class: 'mdl-textfield__label'
          span
            = button_tag(type: 'submit', class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effec")
              i.material-icons done_all

app/views/portfolios/index.html.slim
- provide(:title, 'Portfolios')

.page-content
  .mdl-grid.portfolios
    .mdl-cell.mdl-cell--2-col
    .mdl-cell.mdl-cell--8-col

      div.portfolios__new-portfolio
        = form_for @empty_portfolio, html: { class: 'new-portfolio__form' } do |f|
          .mdl-textfield.mdl-js-textfield.new-portfolio__title-field
            = f.text_field :title, class: 'mdl-textfield__input'
            = f.label      :title, class: 'mdl-textfield__label'
          span
            = button_tag(type: 'submit', class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effec")
              i.material-icons work

      div.portfolios__portfolio-list

        table { class='mdl-data-table mdl-js-data-table mdl-shadow--2dp portfolio-list__portfolios-table' }
          thead
            tr
              th.portfolios-table__cell TITLE
              th.portfolios-table__cell SYMBOLS
              th.portfolios-table__cell COUNT
              th.portfolios-table__cell ACTION
          tbody
            - @portfolios.each do |portfolio|

              tr
                td.portfolios-table__cell
                  = link_to portfolio.title, portfolio_path(id: portfolio.id)
                
                td.portfolios-table__cell
                  = portfolio.stock_list.join(', ')

                td.portfolios-table__cell
                  = portfolio.stock_count

                td.portfolios-table__cell
                  = link_to portfolio_path(id: portfolio.id) do
                    i.material-icons visibility

                  = link_to edit_portfolio_path(id: portfolio.id) do
                    i.material-icons settings

                  = link_to portfolio_path(id: portfolio.id), method: :delete do
                    i.material-icons highlight_off

app/views/portfolios/show.html.slim
- provide(:title, "Portfolio - #{@portfolio.title}")

.page-content
  .mdl-grid.portfolio-data
    .mdl-cell.mdl-cell--4-col.mdl-cell--12-col-tablet.mdl-cell--12-col-phone
      .mdl-grid.mdl-grid--no-spacing
        .portfolio-data__title.mdl-cell.mdl-cell--4-col.mdl-cell--12-col-tablet.mdl-cell--12-col-desktop.mdl-color--white.mdl-shadow--2dp
          div.mdl-typography--title
            span= @portfolio.title

        .portfolio-data__actions.mdl-cell.mdl-cell--4-col.mdl-cell--12-col-tablet.mdl-cell--12-col-desktop
          div.portfolio-data__actions--centerize
            button#portfolio-stock-form-shower.mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect.mdl-button--accent.portfolio-data__action-button
              i.material-icons vertical_align_bottom
              | Stock

            button#portfolio-chart-generator.mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect.mdl-button--accent.portfolio-data__action-button
              i.material-icons trending_up
              | Graphicz

        #stock-form-cell.mdl-cell.mdl-cell--4-col.mdl-cell--12-col-tablet.mdl-cell--12-col-desktop.portfolio-data__stock-form-cell
          = form_for @stock, url: portfolio_stocks_path(portfolio_id: @portfolio.id), html: { class: 'portfolio-data__new-stock-form' } do |f|
            .mdl-textfield.mdl-js-textfield.portfolio-data__symbol-field
              = f.label      :symbol, class: 'mdl-textfield__label'
              = f.text_field :symbol, class: 'mdl-textfield__input'
            span
              = f.submit 'ADD', class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent', name: 'commit'

        .portfolio-data__stock-list.mdl-cell.mdl-cell--4-col.mdl-cell--12-col-tablet.mdl-cell--12-col-desktop
          table{ class='mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp portfolio-data__stock-table' }
            thead
              tr
                th SYMBOL
                th COUNT
                th ACTION
            tbody
              - @portfolio.stocks.each do |stock|
                tr{ data-symbol="#{stock.symbol}" }
                  td.symbol-cell= stock.symbol
                  td= stock.count
                  td= link_to 'DELETE', portfolio_stock_path(portfolio_id: @portfolio.id, id: stock.id), method: :delete

    .mdl-cell.mdl-cell--8-col.mdl-cell--12-col-tablet.mdl-cell-12-col-phone
      .mdl-grid.mdl-grid--no-spacing
        .mdl-cell.mdl-cell--12-col.mdl-color--white.mdl-shadow--2dp
          div.portfolio-data__charts
            div#portfolio-chart.portfolio-data-charts__container