config/routes.rb
Rails.application.routes.draw do
  root 'portfolios#index'
  devise_for :users

  resources :portfolios, except: [:new] do
    resources :stocks, only: [:create, :destroy]
  end
end

app/views/layouts/_navbar.html.slim
header.mdl-layout__header
  .mdl-layout__header-row
    span.mdl-layout-title= "YF - #{yield(:title)}"
    .mdl-layout-spacer
    button#navbar-reserved-menu.mdl-button.mdl-js-button.mdl-button--icon
      i.material-icons
        | more_vert
    ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect.micromenu[for="navbar-reserved-menu"]
      li.mdl-menu__item.micromenu__item[disabled]
        i.material-icons face
        = current_user.email
      li.mdl-menu__item.micromenu__item
        = link_to portfolios_path do
          i.material-icons work
          | PORTFOLIOS
      li.mdl-menu__item.micromenu__item
        = link_to destroy_user_session_path, method: :delete do
          i.material-icons exit_to_app
          | EXIT

app/views/layouts/application.html.slim
doctype html
html.mdl-js lang='en'
  head
    meta content='text/html; charset=UTF-8' http-equiv='Content-Type'
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    title YahooFinanceTask
    = stylesheet_link_tag    'application', media: 'all'
    = Gon::Base.render_data
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body.mdl-base.mdl-color--grey-100.mdl-color-text--grey-700
    .mdl-layout.mdl-js-layout.mdl-layout--fixed-header
      = render 'layouts/navbar' if user_signed_in?
      main.mdl-layout__content
        = yield